import AdminSidebar from "@/components/adminsidebar";
import "react-toastify/dist/ReactToastify.css";
import "../../globals.css";
import type { Metadata } from "next";
import AdminNavbar from "@/components/adminnavbar/adminNavbar";
import { AdminContextProvider } from "@/context/storeAdmin";

export const metadata: Metadata = {
  title: "Pixellab App",
  description: "Generated by Pixellab App",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AdminContextProvider>
      <div className="min-h-screen flex flex-col">
        <div className="w-full">
          <AdminNavbar />
        </div>
        <div className="grid grid-cols-1 gap-4 lg:grid-cols-5 lg:gap-8">
          <div className="flex h-screen flex-col justify-between border-e bg-white">
            <div className="px-4 py-6">
              <AdminSidebar />
            </div>
          </div>
          <div className="lg:col-span-4">{children}</div>
        </div>
      </div>
    </AdminContextProvider>
  );
}
