version: "3.5"
services:
app:
  web:
    build:
    context: .
    dockerfile: Dockefile
    container_name: nextjs-app
    ports:
      - "3000:3800"
    volumes:
      - .:/app/web
      - /app/web/node_modules
