import "../globals.css";
import "react-toastify/dist/ReactToastify.css";
import type { Metadata } from "next";
import Navbar from "@/components/navbar";
import { UserContextProvider } from "@/context/store";

export const metadata: Metadata = {
  title: "Pixellab App",
  description: "Generated by Pixellab App",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <UserContextProvider>
      <div className="min-h-screen flex flex-col">
        <div className="w-full">
          <Navbar />
        </div>
        <div className="flex flex-grow flex-col">{children}</div>
      </div>
    </UserContextProvider>
  );
}
